import { defineConfig } from 'orval'

// The document is generated by the backend build and committed, so the client is generated without a running API.
export default defineConfig({
  castor: {
    input: '../backend/openapi/Castor.Api.json',
    output: {
      target: 'src/api/generated/castor.ts',
      client: 'react-query',
      httpClient: 'fetch',
      clean: true,
      override: {
        mutator: {
          path: 'src/api/castor-fetch.ts',
          name: 'castorFetch',
        },
      },
    },
  },
})
