// <auto-generated />
using System;
using System.Collections.Generic;
using Castor.Api.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Castor.Api.Migrations
{
    [DbContext(typeof(CastorDbContext))]
    partial class CastorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "unaccent");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Castor.Api.Domain.BackgroundJob", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Done")
                        .HasColumnType("integer");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("Failed")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Total")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("BackgroundJobs");
                });

            modelBuilder.Entity("Castor.Api.Domain.ChallengeArea", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Definition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("KeyChallenges")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasAlternateKey("Code")
                        .HasName("AK_ChallengeAreas_Code");

                    b.ToTable("ChallengeAreas");
                });

            modelBuilder.Entity("Castor.Api.Domain.FitAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("DataYear")
                        .HasColumnType("integer");

                    b.Property<string>("Fit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Missing")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<Guid>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ScaleEstimate")
                        .HasColumnType("text");

                    b.Property<string>("ServiceForm")
                        .HasColumnType("text");

                    b.Property<string>("ServiceProvider")
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("ToAdapt")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Unchanged")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("InnovationId", "MunicipalityId", "DataYear")
                        .IsUnique()
                        .HasDatabaseName("IX_FitAssessments_OnePerInnovationMunicipalityAndYear");

                    b.ToTable("FitAssessments");
                });

            modelBuilder.Entity("Castor.Api.Domain.FitAssistantMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("FitAssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("FitAssessmentId", "UserId", "CreatedAt");

                    b.ToTable("FitAssistantMessages");
                });

            modelBuilder.Entity("Castor.Api.Domain.GrantCall", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ChallengeAreaCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateOnly?>("ClosesOn")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.PrimitiveCollection<List<string>>("Criteria")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateOnly?>("OpensOn")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("GrantCalls", t =>
                        {
                            t.HasCheckConstraint("CK_GrantCalls_ClosesAfterOpening", "\"OpensOn\" IS NULL OR \"ClosesOn\" IS NULL OR \"ClosesOn\" >= \"OpensOn\"");
                        });
                });

            modelBuilder.Entity("Castor.Api.Domain.Indicator", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ChallengeAreaCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("General")
                        .HasColumnType("boolean");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("ObserverId")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ObserverId")
                        .IsUnique()
                        .HasDatabaseName("IX_Indicators_UniqueObserverId");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("Castor.Api.Domain.IndicatorValue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IndicatorId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TerritoryCode")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<decimal>("Value")
                        .HasPrecision(19, 8)
                        .HasColumnType("numeric(19,8)");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Level", "TerritoryCode");

                    b.HasIndex("IndicatorId", "Level", "TerritoryCode", "Year")
                        .IsUnique()
                        .HasDatabaseName("IX_IndicatorValues_OnePerTerritoryAndYear");

                    b.ToTable("IndicatorValues");
                });

            modelBuilder.Entity("Castor.Api.Domain.Innovation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Beneficiaries")
                        .HasColumnType("text");

                    b.Property<string>("CardPdfUrl")
                        .HasColumnType("text");

                    b.Property<string>("CardUrl")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("Categories")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Evidence")
                        .HasColumnType("text");

                    b.Property<bool>("Featured")
                        .HasColumnType("boolean");

                    b.Property<bool>("InServiceModel")
                        .HasColumnType("boolean");

                    b.Property<string>("MaterialsZipUrl")
                        .HasColumnType("text");

                    b.Property<string>("Organization")
                        .HasColumnType("text");

                    b.Property<string>("Problems")
                        .HasColumnType("text");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasComputedColumnSql("to_tsvector('simple', castor_unaccent(\n    coalesce(\"Title\", '') || ' ' || coalesce(\"ShortDescription\", '') || ' ' ||\n    coalesce(\"Solution\", '') || ' ' || coalesce(\"Problems\", '') || ' ' ||\n    coalesce(\"TargetGroup\", '') || ' ' || coalesce(\"Beneficiaries\", '')))", true);

                    b.Property<bool>("SeeksTesters")
                        .HasColumnType("boolean");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text");

                    b.Property<string>("Solution")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SourceKey")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Stage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("text");

                    b.Property<string>("TermsUrl")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("VideoUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("IX_Innovations_Search");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SourceKey")
                        .IsUnique()
                        .HasDatabaseName("IX_Innovations_UniqueSourceKey");

                    b.ToTable("Innovations");
                });

            modelBuilder.Entity("Castor.Api.Domain.InnovationGenome", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ChallengeAreaCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid>("InnovationId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Mechanisms")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("RootCauses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Scale")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(600)
                        .HasColumnType("character varying(600)");

                    b.PrimitiveCollection<List<string>>("TargetGroups")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("InnovationId")
                        .IsUnique()
                        .HasDatabaseName("IX_InnovationGenomes_OnePerInnovation");

                    b.ToTable("InnovationGenomes");
                });

            modelBuilder.Entity("Castor.Api.Domain.MatchResult", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Adaptation")
                        .HasColumnType("text");

                    b.PrimitiveCollection<List<string>>("CitedFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("HybridDescription")
                        .HasColumnType("text");

                    b.Property<string>("HybridName")
                        .HasColumnType("text");

                    b.Property<Guid?>("InnovationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Justification")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<Guid>("ProblemReportId")
                        .HasColumnType("uuid");

                    b.Property<int?>("Score")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<Guid>>("SourceInnovationIds")
                        .IsRequired()
                        .HasColumnType("uuid[]");

                    b.HasKey("Id");

                    b.HasIndex("InnovationId");

                    b.HasIndex("ProblemReportId", "Position")
                        .IsUnique()
                        .HasDatabaseName("IX_MatchResults_OnePerPosition");

                    b.ToTable("MatchResults", t =>
                        {
                            t.HasCheckConstraint("CK_MatchResults_KindShape", "(\"Kind\" = 'MATCH' AND \"InnovationId\" IS NOT NULL AND \"Score\" IS NOT NULL) OR (\"Kind\" = 'HYBRID' AND \"InnovationId\" IS NULL AND \"HybridName\" IS NOT NULL)");

                            t.HasCheckConstraint("CK_MatchResults_ScoreRange", "\"Score\" IS NULL OR \"Score\" BETWEEN 0 AND 100");
                        });
                });

            modelBuilder.Entity("Castor.Api.Domain.Municipality", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Powiat")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Teryt")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character(7)")
                        .IsFixedLength();

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Teryt")
                        .IsUnique()
                        .HasDatabaseName("IX_Municipalities_UniqueTeryt");

                    b.ToTable("Municipalities");
                });

            modelBuilder.Entity("Castor.Api.Domain.Persona", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("ChallengeAreaCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<List<string>>("Challenges")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.PrimitiveCollection<List<string>>("Description")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Goals")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Motivations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ChallengeAreaCode");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Personas_UniqueName");

                    b.ToTable("Personas");
                });

            modelBuilder.Entity("Castor.Api.Domain.ProblemReport", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ChallengeAreaCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ClaimedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset?>("ClassifiedAt")
                        .HasColumnType("timestamptz");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(6000)
                        .HasColumnType("character varying(6000)");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset?>("MatchedAt")
                        .HasColumnType("timestamptz");

                    b.Property<Guid?>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("OriginalDescription")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<DateTimeOffset?>("QuestionsSettledAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("ReplyDraft")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("ReplyDraftUpdatedAt")
                        .HasColumnType("timestamptz");

                    b.PrimitiveCollection<List<string>>("RootCauses")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("SubmittedOnBehalf")
                        .HasColumnType("boolean");

                    b.Property<string>("TargetGroup")
                        .HasColumnType("text");

                    b.Property<string>("TrackingCode")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character(8)")
                        .IsFixedLength();

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Urgency")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("MunicipalityId");

                    b.HasIndex("TrackingCode")
                        .IsUnique()
                        .HasDatabaseName("IX_ProblemReports_UniqueTrackingCode");

                    b.ToTable("ProblemReports");
                });

            modelBuilder.Entity("Castor.Api.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("ChallengeAreaCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("character varying(254)");

                    b.Property<Guid?>("MunicipalityId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("MunicipalityId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Castor.Api.Domain.FitAssessment", b =>
                {
                    b.HasOne("Castor.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Castor.Api.Domain.Innovation", "Innovation")
                        .WithMany()
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Castor.Api.Domain.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsMany("Castor.Api.Domain.FitComparisonRow", "Comparison", b1 =>
                        {
                            b1.Property<Guid>("FitAssessmentId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("IndicatorName")
                                .IsRequired();

                            b1.Property<string>("Level")
                                .IsRequired();

                            b1.Property<decimal>("RegionAverage")
                                .HasPrecision(19, 4);

                            b1.Property<string>("Requirement")
                                .IsRequired();

                            b1.Property<string>("Unit");

                            b1.Property<decimal>("Value")
                                .HasPrecision(19, 4);

                            b1.Property<int>("Year");

                            b1.HasKey("FitAssessmentId", "__synthesizedOrdinal");

                            b1.ToTable("FitAssessments");

                            b1
                                .ToJson("Comparison")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FitAssessmentId");
                        });

                    b.Navigation("Comparison");

                    b.Navigation("Innovation");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Castor.Api.Domain.FitAssistantMessage", b =>
                {
                    b.HasOne("Castor.Api.Domain.FitAssessment", null)
                        .WithMany()
                        .HasForeignKey("FitAssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Castor.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Castor.Api.Domain.IndicatorValue", b =>
                {
                    b.HasOne("Castor.Api.Domain.Indicator", null)
                        .WithMany()
                        .HasForeignKey("IndicatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Castor.Api.Domain.InnovationGenome", b =>
                {
                    b.HasOne("Castor.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Castor.Api.Domain.Innovation", null)
                        .WithOne("Genome")
                        .HasForeignKey("Castor.Api.Domain.InnovationGenome", "InnovationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Castor.Api.Domain.RequiredResources", "RequiredResources", b1 =>
                        {
                            b1.Property<Guid>("InnovationGenomeId");

                            b1.Property<string>("Budget");

                            b1.PrimitiveCollection<string>("Infrastructure")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("Institutions")
                                .IsRequired();

                            b1.PrimitiveCollection<string>("People")
                                .IsRequired();

                            b1.HasKey("InnovationGenomeId");

                            b1.ToTable("InnovationGenomes");

                            b1
                                .ToJson("RequiredResources")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("InnovationGenomeId");
                        });

                    b.Navigation("RequiredResources")
                        .IsRequired();
                });

            modelBuilder.Entity("Castor.Api.Domain.MatchResult", b =>
                {
                    b.HasOne("Castor.Api.Domain.Innovation", "Innovation")
                        .WithMany()
                        .HasForeignKey("InnovationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Castor.Api.Domain.ProblemReport", null)
                        .WithMany()
                        .HasForeignKey("ProblemReportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Innovation");
                });

            modelBuilder.Entity("Castor.Api.Domain.Persona", b =>
                {
                    b.HasOne("Castor.Api.Domain.ChallengeArea", null)
                        .WithMany()
                        .HasForeignKey("ChallengeAreaCode")
                        .HasPrincipalKey("Code")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Castor.Api.Domain.ProblemReport", b =>
                {
                    b.HasOne("Castor.Api.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Castor.Api.Domain.Municipality", "Municipality")
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsMany("Castor.Api.Domain.ClarifyingQuestion", "ClarifyingQuestions", b1 =>
                        {
                            b1.Property<Guid>("ProblemReportId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Answer");

                            b1.Property<string>("Question")
                                .IsRequired();

                            b1.HasKey("ProblemReportId", "__synthesizedOrdinal");

                            b1.ToTable("ProblemReports");

                            b1
                                .ToJson("ClarifyingQuestions")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("ProblemReportId");
                        });

                    b.Navigation("ClarifyingQuestions");

                    b.Navigation("Municipality");
                });

            modelBuilder.Entity("Castor.Api.Domain.User", b =>
                {
                    b.HasOne("Castor.Api.Domain.Municipality", null)
                        .WithMany()
                        .HasForeignKey("MunicipalityId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Castor.Api.Domain.Innovation", b =>
                {
                    b.Navigation("Genome");
                });
#pragma warning restore 612, 618
        }
    }
}
